# Generated by Django 5.2.4 on 2025-08-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planthealthreport',
            name='confidence',
        ),
        migrations.AlterField(
            model_name='planthealthreport',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planthealthreport',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
