# Generated by Django 5.2.4 on 2025-08-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=100)),
                ('organizationName', models.CharField(max_length=150)),
                ('contactName', models.CharField(max_length=100)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('contactPhone', models.CharField(max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('benefits', models.TextField()),
                ('documents', models.TextField(help_text='List required documents')),
                ('applicationProcess', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('tags', models.CharField(help_text='Comma-separated tags', max_length=255)),
            ],
        ),
    ]
