# Generated by Django 5.2.4 on 2025-08-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='written_user',
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, help_text='Brief summary of the article', max_length=500, null=True),
        ),
    ]
