# Generated by Django 5.2.4 on 2025-08-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_written_user_article_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_pps_photo',
        ),
    ]
