# Generated by Django 5.2.4 on 2025-08-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_user_pps_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='popular_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
